/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ActiveCaseArchiveFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "AuthUserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaseMaterialBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RegistrationWorkflowTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StudentCaseCompletionTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StudentCertificateTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StudentQuizAttemptTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TeacherCaseTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserProfileTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "eccsfeweb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}